
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClassLibraryMedAc
{

using System;
    using System.Collections.Generic;
    
public partial class Alertas
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Alertas()
    {

        this.Valores = new HashSet<Valores>();

    }


    public int Id { get; set; }

    public string Tipo { get; set; }

    public System.DateTime Data { get; set; }

    public string Read { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Valores> Valores { get; set; }

}

}
