//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryMedAc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alertas
    {
        public int Id { get; set; }
        public string Tipo { get; set; }
        public System.DateTime Data { get; set; }
        public string Read { get; set; }
        public string Parametro { get; set; }
    
        public virtual Utente Utente { get; set; }
    }
}
