//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryMedAc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valores
    {
        public int Id { get; set; }
        public string BloodPressure { get; set; }
        public string HeartRate { get; set; }
        public string OxygenSaturation { get; set; }
    
        public virtual Utente Utente { get; set; }
        public virtual Alertas Alertas { get; set; }
    }
}
